config/routes.rb
Tinyurl::Application.routes.draw do
  root :to => redirect("/urls/new")
	resources :urls, :only => [:show, :new, :create]

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :url
	validates :url, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
		@tiny_url = Url.new
  end

	def create
		@tiny_url = Url.new params[:url]
		if @tiny_url.save
			flash[:tiny_id] = @tiny_url.id
			redirect_to new_url_url
		else
			render :action => "new"
		end
	end

	def show
		@tiny_url = Url.find params[:id]
		redirect_to @tiny_url.url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tinyurl</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:tiny_id].present? %>
	<p class='tiny-url'>
		Follow the tiny <%= link_to url_url(flash[:tiny_id]), url_url(flash[:tiny_id]) %>
	</p>
<% end %>
<%= yield %>

</body>
</html>

app/views/urls/new.html.haml
.container
	%h1 Submit your URL, and receive a tiny URL
	=form_for @tiny_url do |f|
		%p
			= f.label :url, "URL?"
			= f.text_field :url
		- if @tiny_url.errors[:url].any?
			%p.error-messages
				= @tiny_url.errors[:url].to_sentence

		%p.btn.btn-success.btn-large
			= f.submit "Get a tiny URL"